# Generated by Django 5.2.6 on 2026-09-21 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("principal", "0005_ordencompra"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="stock",
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.CreateModel(
            name="DetalleOrdenCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_producto", models.CharField(max_length=120)),
                ("cantidad", models.PositiveIntegerField()),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "orden",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="principal.ordencompra",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="principal.producto",
                    ),
                ),
            ],
        ),
    ]
